gateways:
  duckdb:
    connection:
      type: duckdb
      database: db.db

default_gateway: duckdb

model_defaults:
  dialect: duckdb
  start: 2018-01-01
  # audits: [assert_positive_order_ids]

linter:
  enabled: true
  # rules: ["ambiguousorinvalidcolumn", "invalidselectstarexpansion"] # raise errors for these rules
  # warn_rules: ["nomissingaudits"]
  # ignored_rules: ["noselectstar"]