gateways:
  duckdb:
    connection:
      type: duckdb
      database: db.db

default_gateway: duckdb

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults
model_defaults:
  dialect: duckdb
  start: 2018-01-01
  # audits: [assert_positive_order_ids]

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/
linter:
  enabled: true
  rules: ["ambiguousorinvalidcolumn", "invalidselectstarexpansion"] # raise errors for these rules
  # warn_rules: ["nomissingaudits"]
  # ignored_rules: ["noselectstar"]